#!/usr/bin/env bash

xcode_proj=`find . -name "*.xcodeproj" -or -name "*.xcworkspace" -maxdepth 1 | sort -r | head -1`

if [ `echo -n $xcode_proj | wc -m` == 0 ]
then
    echo "No xcworkspace/xcodeproj file found in the current directory."
else
    echo "Found $xcode_proj"
    open "$xcode_proj"
fi
